debug: true
lightningredstone:
    enabled: false
    try-frequency: 600
    start-delay: 200
    run-chance: 100
    overload-chance: 100
    overload-power: 3
catsanddogs:
    enabled: true
    run-chance: 100
    event-length: 10
    spawn-height: 30