debug: false
global:
    try-frequency: 600
    start-delay: 200
lightningredstone:
    enabled: true
    run-chance: 10
    overload-chance: 100
    overload-power: 3
catsanddogs:
    enabled: true
    run-chance: 45
    event-length: 15
    spawn-height: 45